version: "3.9"
services:
  timecards-api:
    image: timecards-api:${TAG:-latest}
    build:
      context: Src/
      dockerfile: timecards/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://*:80
    restart: always
    ports:
      - 5100:80
    depends_on:
      - timecards-db
    links:
      - timecards-db
    networks:
      - timecards-net

  timecards-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Password1!
      - ACCEPT_EULA=Y
    ports:
      - 2433:1433
    networks:
      - timecards-net
    
networks:
  timecards-net:
    driver: bridge
